--- 
name: build
on: [push, pull_request]
jobs:
  std_tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - name: Run linter
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools
          python -m pip install tox
      - name: run tox
        run: python -m tox -e cicd --skip-missing-interpreters=true
